/**
 * Configuration-driven Admin panel.
 *
 * Every section below is generated from this file: the list table, the filters,
 * the create/edit form and the workflow buttons. Adding a section means adding a
 * config entry, not writing a page — which is how the owner gets ~30 working
 * admin screens that all behave identically.
 */

export type FieldType =
  | 'text' | 'textarea' | 'longtext' | 'number' | 'money' | 'bool'
  | 'select' | 'date' | 'datetime' | 'json' | 'relation' | 'image' | 'readonly';

export interface AdminField {
  name: string;
  label: string;
  type: FieldType;
  help?: string;
  required?: boolean;
  options?: { value: string; label: string }[];
  /** For `relation`: the table to read id/label from. */
  relation?: { table: string; labelColumn: string; where?: string };
  placeholder?: string;
  step?: number;
  group?: string;
  /** Hide from the create form (e.g. computed columns). */
  createOnly?: boolean;
  editOnly?: boolean;
}

export interface AdminColumn {
  name: string;
  label: string;
  type?: 'text' | 'money' | 'bool' | 'date' | 'badge' | 'number';
  /** Raw SQL expression, when the column is not a plain field. */
  expr?: string;
}

export interface AdminAction {
  key: string;
  label: string;
  /** Sets these columns. `$now` and `$user` are substituted server-side. */
  set: Record<string, string | number | null>;
  /** Requires a typed reason, stored in this column. */
  reasonColumn?: string;
  tone?: 'primary' | 'danger' | 'neutral' | 'success';
  /** Only offer the action when the row is in one of these statuses. */
  when?: { column: string; in: string[] };
  /** Notification sent to the row owner, if the resource declares an owner column. */
  notify?: { event: string; title: string; body: string };
  permission?: string;
}

export interface AdminResource {
  key: string;
  table: string;
  label: string;
  plural: string;
  group: string;
  description: string;
  /** Column used as the human label of a row. */
  titleColumn: string;
  /** Extra SELECT expressions joined into the list query. */
  listSelect?: string;
  listJoin?: string;
  listWhere?: string;
  columns: AdminColumn[];
  searchColumns: string[];
  filters?: { name: string; label: string; column: string; options: string[] }[];
  defaultSort?: string;
  fields: AdminField[];
  actions?: AdminAction[];
  permission: string;
  canCreate?: boolean;
  canDelete?: boolean;
  softDelete?: boolean;
  /** Column holding the user id to notify on workflow actions. */
  ownerColumn?: string;
  /** Route on the public site, for a "view live" link. `{slug}` is substituted. */
  publicPath?: string;
}

const STATUS_BADGE = (name = 'status', label = 'Status'): AdminColumn => ({ name, label, type: 'badge' });

const sel = (...values: string[]) => values.map((v) => ({ value: v, label: v.replace(/_/g, ' ') }));

export const ADMIN_RESOURCES: AdminResource[] = [
  // ─────────────────────────── Catalogue ───────────────────────────
  {
    key: 'products',
    table: 'products',
    label: 'Product',
    plural: 'Products',
    group: 'Catalogue',
    description: 'Every bike, EV bike and EV scooter in the database. Specs live on the product edit screen.',
    titleColumn: 'name',
    listSelect: 'b.name AS brand_name',
    listJoin: 'LEFT JOIN brands b ON b.id = t.brand_id',
    columns: [
      { name: 'name', label: 'Model' },
      { name: 'brand_name', label: 'Brand' },
      { name: 'fuel_type', label: 'Fuel', type: 'badge' },
      { name: 'body_type', label: 'Body' },
      { name: 'price_min', label: 'Ex-showroom price', type: 'money' },
      { name: 'score', label: 'Score', type: 'number' },
      STATUS_BADGE(),
      { name: 'is_demo', label: 'Demo', type: 'bool' },
    ],
    searchColumns: ['t.name', 't.slug', 'b.name'],
    filters: [
      { name: 'status', label: 'Status', column: 't.status', options: ['draft', 'published', 'unpublished', 'archived'] },
      { name: 'fuel_type', label: 'Fuel', column: 't.fuel_type', options: ['petrol', 'electric'] },
    ],
    defaultSort: 't.updated_at DESC',
    fields: [
      { name: 'name', label: 'Model name', type: 'text', required: true, group: 'Basics' },
      { name: 'slug', label: 'URL slug', type: 'text', help: 'Leave blank to generate from the name.', group: 'Basics' },
      { name: 'brand_id', label: 'Brand', type: 'relation', required: true, relation: { table: 'brands', labelColumn: 'name' }, group: 'Basics' },
      { name: 'category_id', label: 'Category', type: 'relation', relation: { table: 'categories', labelColumn: 'name' }, group: 'Basics' },
      { name: 'fuel_type', label: 'Fuel type', type: 'select', required: true, options: sel('petrol', 'electric'), group: 'Basics' },
      { name: 'body_type', label: 'Body type', type: 'select', options: sel('commuter', 'sport', 'street', 'cruiser', 'adventure', 'scooter'), group: 'Basics' },
      { name: 'model_year', label: 'Model year', type: 'number', group: 'Basics' },
      { name: 'generation', label: 'Generation', type: 'text', group: 'Basics' },
      { name: 'description', label: 'Description', type: 'longtext', group: 'Editorial' },
      { name: 'best_for', label: 'Best for', type: 'text', group: 'Editorial' },
      { name: 'status', label: 'Status', type: 'select', required: true, options: sel('draft', 'published', 'unpublished', 'archived'), group: 'Publishing' },
      { name: 'featured', label: 'Featured on homepage', type: 'bool', group: 'Publishing' },
      { name: 'is_demo', label: 'Demo data', type: 'bool', help: 'Shows a Demo badge everywhere and is removed by the demo purge.', group: 'Publishing' },
    ],
    actions: [
      { key: 'publish', label: 'Publish', set: { status: 'published', published_at: '$now' }, tone: 'success', when: { column: 'status', in: ['draft', 'unpublished'] } },
      { key: 'unpublish', label: 'Unpublish', set: { status: 'unpublished' }, tone: 'neutral', when: { column: 'status', in: ['published'] } },
    ],
    permission: 'product.write',
    canCreate: true, canDelete: true, softDelete: true,
    publicPath: '/bikes',
  },
  {
    key: 'brands',
    table: 'brands',
    label: 'Brand',
    plural: 'Brands',
    group: 'Catalogue',
    description: 'Manufacturer records. Logos must only be used where you hold the rights.',
    titleColumn: 'name',
    columns: [
      { name: 'name', label: 'Brand' },
      { name: 'country', label: 'Country' },
      { name: 'logo_url', label: 'Logo' },
      { name: 'logo_license', label: 'Logo licence' },
      { name: 'product_count', label: 'Models', type: 'number', expr: '(SELECT COUNT(*) FROM products p WHERE p.brand_id = t.id AND p.deleted_at IS NULL)' },
    ],
    searchColumns: ['t.name', 't.slug'],
    defaultSort: 't.name',
    fields: [
      { name: 'name', label: 'Brand name', type: 'text', required: true },
      { name: 'slug', label: 'URL slug', type: 'text' },
      { name: 'country', label: 'Country', type: 'text' },
      { name: 'logo_url', label: 'Logo URL', type: 'text', help: 'Only add a logo you have the rights to use.' },
      { name: 'logo_source', label: 'Logo source', type: 'text' },
      { name: 'logo_license', label: 'Logo licence status', type: 'select', options: sel('unknown', 'owned', 'licensed', 'press_kit', 'not_permitted') },
      { name: 'website', label: 'Official website', type: 'text' },
      { name: 'about', label: 'About', type: 'textarea' },
    ],
    permission: 'product.write',
    canCreate: true, canDelete: true, softDelete: true,
  },
  {
    key: 'categories',
    table: 'categories',
    label: 'Category',
    plural: 'Categories',
    group: 'Catalogue',
    description: 'Top-level categories. Mobile and Electronics stay disabled until you activate them here.',
    titleColumn: 'name',
    columns: [
      { name: 'name', label: 'Category' },
      { name: 'slug', label: 'Slug' },
      { name: 'active', label: 'Active', type: 'bool' },
      { name: 'sort_order', label: 'Order', type: 'number' },
    ],
    searchColumns: ['t.name', 't.slug'],
    defaultSort: 't.sort_order',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'icon', label: 'Icon key', type: 'text' },
      { name: 'active', label: 'Active on the public site', type: 'bool', help: 'Turning a category on makes it appear in navigation and search.' },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
    ],
    permission: 'product.write',
    canCreate: true, canDelete: false,
  },
  {
    key: 'variants',
    table: 'product_variants',
    label: 'Variant',
    plural: 'Variants',
    group: 'Catalogue',
    description: 'Trim levels and their prices.',
    titleColumn: 'name',
    listSelect: 'p.name AS product_name',
    listJoin: 'LEFT JOIN products p ON p.id = t.product_id',
    columns: [
      { name: 'product_name', label: 'Model' },
      { name: 'name', label: 'Variant' },
      { name: 'price', label: 'Ex-showroom', type: 'money' },
      { name: 'on_road_price', label: 'On-road', type: 'money' },
      { name: 'is_base', label: 'Base', type: 'bool' },
      STATUS_BADGE(),
    ],
    searchColumns: ['t.name', 'p.name'],
    defaultSort: 'p.name, t.sort_order',
    fields: [
      { name: 'product_id', label: 'Model', type: 'relation', required: true, relation: { table: 'products', labelColumn: 'name' } },
      { name: 'name', label: 'Variant name', type: 'text', required: true },
      { name: 'variant_code', label: 'Variant code', type: 'text' },
      { name: 'price', label: 'Ex-showroom price (₹)', type: 'money' },
      { name: 'on_road_price', label: 'On-road price (₹)', type: 'money' },
      { name: 'colours', label: 'Colours (comma separated)', type: 'text' },
      { name: 'highlights', label: 'Highlights', type: 'textarea' },
      { name: 'is_base', label: 'Base variant', type: 'bool' },
      { name: 'is_new', label: 'Mark as “New” (shown on the variant table when the OEM tags it new)', type: 'bool' },
      { name: 'status', label: 'Status', type: 'select', options: sel('active', 'discontinued') },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
    ],
    permission: 'product.write',
    canCreate: true, canDelete: true, softDelete: true,
  },
  {
    key: 'price-history',
    table: 'price_history',
    label: 'Price record',
    plural: 'Price history',
    group: 'Catalogue',
    description: 'Every recorded price point. Price-drop alerts are evaluated against this table.',
    titleColumn: 'price',
    listSelect: 'p.name AS product_name',
    listJoin: 'LEFT JOIN products p ON p.id = t.product_id',
    columns: [
      { name: 'product_name', label: 'Model' },
      { name: 'price', label: 'Price', type: 'money' },
      { name: 'price_type', label: 'Type', type: 'badge' },
      { name: 'city', label: 'City' },
      { name: 'source_name', label: 'Source' },
      { name: 'verified', label: 'Verified', type: 'bool' },
      { name: 'recorded_at', label: 'Recorded', type: 'date' },
    ],
    searchColumns: ['p.name', 't.city', 't.source_name'],
    defaultSort: 't.recorded_at DESC',
    fields: [
      { name: 'product_id', label: 'Model', type: 'relation', required: true, relation: { table: 'products', labelColumn: 'name' } },
      { name: 'price', label: 'Price (₹)', type: 'money', required: true },
      { name: 'price_type', label: 'Price type', type: 'select', options: sel('ex_showroom', 'on_road', 'street') },
      { name: 'city', label: 'City', type: 'text' },
      { name: 'source_name', label: 'Source name', type: 'text', required: true, help: 'Where this price came from. Required for traceability.' },
      { name: 'source_url', label: 'Source URL', type: 'text' },
      { name: 'verified', label: 'Verified by staff', type: 'bool' },
      { name: 'recorded_at', label: 'Recorded at', type: 'datetime' },
    ],
    permission: 'product.write',
    canCreate: true, canDelete: true,
  },
  {
    key: 'images',
    table: 'product_images',
    label: 'Image',
    plural: 'Product images',
    group: 'Catalogue',
    description: 'Image library. Every image records its source and licence status.',
    titleColumn: 'image_url',
    listSelect: 'p.name AS product_name',
    listJoin: 'LEFT JOIN products p ON p.id = t.product_id',
    columns: [
      { name: 'product_name', label: 'Model' },
      { name: 'image_url', label: 'Image' },
      { name: 'image_type', label: 'Type', type: 'badge' },
      { name: 'license_status', label: 'Licence', type: 'badge' },
      { name: 'sort_order', label: 'Order', type: 'number' },
    ],
    searchColumns: ['p.name', 't.image_url'],
    defaultSort: 'p.name, t.sort_order',
    fields: [
      { name: 'product_id', label: 'Model', type: 'relation', required: true, relation: { table: 'products', labelColumn: 'name' } },
      { name: 'image_url', label: 'Image', type: 'image', required: true },
      { name: 'alt_text', label: 'Alt text', type: 'text', help: 'Describe the image for screen readers.' },
      { name: 'image_type', label: 'Type', type: 'select', options: sel('main', 'gallery', 'colour', 'detail') },
      { name: 'source', label: 'Source', type: 'text' },
      { name: 'license_status', label: 'Licence status', type: 'select', options: sel('unknown', 'owned', 'licensed', 'press_kit', 'placeholder') },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
    ],
    permission: 'product.write',
    canCreate: true, canDelete: true,
  },

  // ─────────────────────────── Marketplace ───────────────────────────
  {
    key: 'used-bikes',
    table: 'used_bikes',
    label: 'Used listing',
    plural: 'Used bikes',
    group: 'Marketplace',
    description: 'Seller listings and their approval workflow. Nothing is public until it is approved here.',
    titleColumn: 'model_name',
    listSelect: "t.brand_name || ' ' || t.model_name AS title, u.email AS seller_email",
    listJoin: 'LEFT JOIN users u ON u.id = t.seller_id',
    columns: [
      { name: 'title', label: 'Listing' },
      { name: 'city', label: 'City' },
      { name: 'asking_price', label: 'Asking', type: 'money' },
      { name: 'trust_score', label: 'Trust', type: 'number' },
      STATUS_BADGE(),
      { name: 'seller_email', label: 'Seller' },
      { name: 'created_at', label: 'Listed', type: 'date' },
    ],
    searchColumns: ['t.brand_name', 't.model_name', 't.city', 'u.email'],
    filters: [
      { name: 'status', label: 'Status', column: 't.status', options: ['draft', 'submitted', 'verification_required', 'under_review', 'approved', 'needs_more_info', 'rejected', 'suspended', 'sold', 'expired'] },
    ],
    defaultSort: "CASE t.status WHEN 'verification_required' THEN 0 WHEN 'under_review' THEN 1 WHEN 'submitted' THEN 2 ELSE 3 END, t.created_at DESC",
    fields: [
      { name: 'brand_name', label: 'Brand', type: 'text', required: true },
      { name: 'model_name', label: 'Model', type: 'text', required: true },
      { name: 'variant_name', label: 'Variant', type: 'text' },
      { name: 'manufacture_year', label: 'Year', type: 'number' },
      { name: 'km_driven', label: 'Kilometres', type: 'number' },
      { name: 'owners', label: 'Owners', type: 'number' },
      { name: 'city', label: 'City', type: 'text' },
      { name: 'asking_price', label: 'Asking price (₹)', type: 'money' },
      { name: 'condition_grade', label: 'Condition', type: 'select', options: sel('excellent', 'good', 'fair', 'needs_work') },
      { name: 'description', label: 'Description', type: 'longtext' },
      { name: 'status', label: 'Status', type: 'select', options: sel('draft', 'submitted', 'verification_required', 'under_review', 'approved', 'needs_more_info', 'rejected', 'suspended', 'sold', 'expired') },
      { name: 'featured', label: 'Featured listing', type: 'bool' },
      { name: 'is_demo', label: 'Demo data', type: 'bool' },
    ],
    actions: [
      { key: 'review', label: 'Start review', set: { status: 'under_review' }, tone: 'neutral', when: { column: 'status', in: ['submitted', 'verification_required', 'needs_more_info'] }, permission: 'used_bike.review' },
      { key: 'approve', label: 'Approve & publish', set: { status: 'approved', approved_at: '$now', approved_by: '$user' }, tone: 'success', when: { column: 'status', in: ['submitted', 'verification_required', 'under_review', 'needs_more_info', 'suspended'] }, permission: 'used_bike.review',
        notify: { event: 'used_bike_approved', title: 'Your listing is live', body: 'Your used-bike listing passed review and is now visible to buyers.' } },
      { key: 'info', label: 'Request more info', set: { status: 'needs_more_info' }, reasonColumn: 'info_request', tone: 'neutral', when: { column: 'status', in: ['submitted', 'verification_required', 'under_review'] }, permission: 'used_bike.review',
        notify: { event: 'used_bike_info_required', title: 'We need a bit more information', body: 'Open your listing to see exactly what is missing.' } },
      { key: 'reject', label: 'Reject', set: { status: 'rejected' }, reasonColumn: 'rejection_reason', tone: 'danger', when: { column: 'status', in: ['submitted', 'verification_required', 'under_review', 'needs_more_info', 'approved'] }, permission: 'used_bike.review',
        notify: { event: 'used_bike_rejected', title: 'Your listing was not approved', body: 'Open your listing to see the reason.' } },
      { key: 'suspend', label: 'Suspend', set: { status: 'suspended' }, reasonColumn: 'rejection_reason', tone: 'danger', when: { column: 'status', in: ['approved'] }, permission: 'used_bike.review' },
    ],
    permission: 'used_bike.review',
    ownerColumn: 'seller_id',
    canCreate: false, canDelete: true, softDelete: true,
    publicPath: '/used-bikes',
  },
  {
    key: 'verifications',
    table: 'verification_records',
    label: 'Verification check',
    plural: 'Verification checks',
    group: 'Marketplace',
    description: 'Individual checks behind every trust score. Only "passed" earns points.',
    titleColumn: 'check_type',
    columns: [
      { name: 'entity_type', label: 'Entity', type: 'badge' },
      { name: 'entity_id', label: 'Entity ID' },
      { name: 'check_type', label: 'Check' },
      { name: 'result', label: 'Result', type: 'badge' },
      { name: 'method', label: 'Method' },
      { name: 'performed_at', label: 'Performed', type: 'date' },
    ],
    searchColumns: ['t.entity_id', 't.check_type'],
    filters: [{ name: 'result', label: 'Result', column: 't.result', options: ['not_checked', 'passed', 'failed', 'unavailable'] }],
    defaultSort: 't.updated_at DESC',
    fields: [
      { name: 'entity_type', label: 'Entity type', type: 'select', required: true, options: sel('used_bike', 'dealer') },
      { name: 'entity_id', label: 'Entity ID', type: 'text', required: true },
      { name: 'check_type', label: 'Check type', type: 'select', required: true, options: sel('seller_identity', 'ownership_declaration', 'rc_verification', 'insurance_verification', 'loan_status', 'service_history', 'photo_authenticity', 'physical_inspection', 'business_registration', 'address_proof') },
      { name: 'result', label: 'Result', type: 'select', required: true, options: sel('not_checked', 'passed', 'failed', 'unavailable') },
      { name: 'method', label: 'Method', type: 'select', options: sel('document_review', 'phone_call', 'physical_visit', 'third_party', 'other') },
      { name: 'evidence_note', label: 'Evidence note', type: 'textarea', help: 'What you saw. Never paste document numbers here.' },
      { name: 'performed_at', label: 'Performed at', type: 'datetime' },
    ],
    permission: 'verification.write',
    canCreate: true, canDelete: true,
  },
  {
    key: 'inspections',
    table: 'inspections',
    label: 'Inspection',
    plural: 'Inspections',
    group: 'Marketplace',
    description: 'Booked physical inspections and their reports.',
    titleColumn: 'id',
    columns: [
      { name: 'used_bike_id', label: 'Listing' },
      { name: 'city', label: 'City' },
      { name: 'preferred_date', label: 'Preferred', type: 'date' },
      { name: 'scheduled_at', label: 'Scheduled', type: 'date' },
      STATUS_BADGE(),
      { name: 'fee', label: 'Fee', type: 'money' },
    ],
    searchColumns: ['t.used_bike_id', 't.city'],
    filters: [{ name: 'status', label: 'Status', column: 't.status', options: ['requested', 'scheduled', 'completed', 'cancelled'] }],
    defaultSort: 't.created_at DESC',
    fields: [
      { name: 'used_bike_id', label: 'Listing ID', type: 'text' },
      { name: 'city', label: 'City', type: 'text' },
      { name: 'preferred_date', label: 'Preferred date', type: 'date' },
      { name: 'scheduled_at', label: 'Scheduled at', type: 'datetime' },
      { name: 'inspector_id', label: 'Inspector', type: 'relation', relation: { table: 'users', labelColumn: 'email' } },
      { name: 'fee', label: 'Fee (₹)', type: 'money' },
      { name: 'status', label: 'Status', type: 'select', options: sel('requested', 'scheduled', 'completed', 'cancelled') },
      { name: 'report', label: 'Inspection report', type: 'longtext', help: 'Findings shown to the buyer who booked it.' },
    ],
    actions: [
      { key: 'complete', label: 'Mark completed', set: { status: 'completed' }, tone: 'success', when: { column: 'status', in: ['scheduled'] } },
      { key: 'cancel', label: 'Cancel', set: { status: 'cancelled' }, tone: 'danger', when: { column: 'status', in: ['requested', 'scheduled'] } },
    ],
    permission: 'verification.write',
    canCreate: true, canDelete: true,
  },

  // ─────────────────────────── Dealers ───────────────────────────
  {
    key: 'dealers',
    table: 'dealer_profiles',
    label: 'Dealer',
    plural: 'Dealers',
    group: 'Dealers',
    description: 'Dealer applications and verified dealerships.',
    titleColumn: 'business_name',
    columns: [
      { name: 'business_name', label: 'Dealership' },
      { name: 'city', label: 'City' },
      { name: 'phone', label: 'Phone' },
      STATUS_BADGE(),
      { name: 'offer_count', label: 'Offers', type: 'number', expr: "(SELECT COUNT(*) FROM dealer_offers o WHERE o.dealer_id = t.id AND o.status='approved' AND o.deleted_at IS NULL)" },
      { name: 'lead_count', label: 'Leads', type: 'number', expr: '(SELECT COUNT(*) FROM leads l WHERE l.dealer_id = t.id)' },
      { name: 'is_demo', label: 'Demo', type: 'bool' },
    ],
    searchColumns: ['t.business_name', 't.city', 't.email', 't.phone'],
    filters: [{ name: 'status', label: 'Status', column: 't.status', options: ['pending', 'verified', 'rejected', 'suspended'] }],
    defaultSort: "CASE t.status WHEN 'pending' THEN 0 ELSE 1 END, t.created_at DESC",
    fields: [
      { name: 'business_name', label: 'Dealership name', type: 'text', required: true },
      { name: 'dealer_name', label: 'Contact person', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'gstin', label: 'GSTIN', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'city', label: 'City', type: 'text' },
      { name: 'state', label: 'State', type: 'text' },
      { name: 'pincode', label: 'Pincode', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', options: sel('pending', 'verified', 'rejected', 'suspended') },
      { name: 'featured', label: 'Featured dealer', type: 'bool', help: 'Paid placement. Labelled Sponsored publicly; never affects scores.' },
      { name: 'about', label: 'About', type: 'textarea' },
      { name: 'is_demo', label: 'Demo data', type: 'bool' },
    ],
    actions: [
      { key: 'verify', label: 'Verify dealer', set: { status: 'verified', verified_at: '$now', verified_by: '$user' }, tone: 'success', when: { column: 'status', in: ['pending', 'suspended', 'rejected'] }, permission: 'dealer.review',
        notify: { event: 'dealer_verified', title: 'Your dealership is verified', body: 'You can now publish offers and receive buyer enquiries.' } },
      { key: 'reject', label: 'Reject', set: { status: 'rejected' }, reasonColumn: 'rejection_reason', tone: 'danger', when: { column: 'status', in: ['pending', 'verified'] }, permission: 'dealer.review',
        notify: { event: 'dealer_rejected', title: 'Dealer application not approved', body: 'Open your dealer dashboard to see the reason.' } },
      { key: 'suspend', label: 'Suspend', set: { status: 'suspended' }, reasonColumn: 'rejection_reason', tone: 'danger', when: { column: 'status', in: ['verified'] }, permission: 'dealer.review' },
    ],
    permission: 'dealer.review',
    ownerColumn: 'user_id',
    canCreate: false, canDelete: true, softDelete: true,
  },
  {
    key: 'offers',
    table: 'dealer_offers',
    label: 'Dealer offer',
    plural: 'Dealer offers',
    group: 'Dealers',
    description: 'Offer approval queue. Approved offers expire automatically on their end date.',
    titleColumn: 'offer_text',
    listSelect: 'd.business_name, p.name AS product_name',
    listJoin: 'LEFT JOIN dealer_profiles d ON d.id = t.dealer_id LEFT JOIN products p ON p.id = t.product_id',
    columns: [
      { name: 'business_name', label: 'Dealer' },
      { name: 'product_name', label: 'Model' },
      { name: 'city', label: 'City' },
      { name: 'discount', label: 'Discount', type: 'money' },
      { name: 'end_date', label: 'Ends', type: 'date' },
      STATUS_BADGE(),
    ],
    searchColumns: ['d.business_name', 'p.name', 't.city', 't.offer_text'],
    filters: [{ name: 'status', label: 'Status', column: 't.status', options: ['pending', 'approved', 'rejected', 'expired', 'withdrawn'] }],
    defaultSort: "CASE t.status WHEN 'pending' THEN 0 ELSE 1 END, t.created_at DESC",
    fields: [
      { name: 'offer_text', label: 'Offer text', type: 'textarea', required: true },
      { name: 'city', label: 'City', type: 'text' },
      { name: 'discount', label: 'Cash discount (₹)', type: 'money' },
      { name: 'exchange_bonus', label: 'Exchange bonus (₹)', type: 'money' },
      { name: 'on_road', label: 'Quoted on-road (₹)', type: 'money' },
      { name: 'finance_offer', label: 'Finance offer', type: 'text' },
      { name: 'accessories_offer', label: 'Accessories offer', type: 'text' },
      { name: 'start_date', label: 'Valid from', type: 'date' },
      { name: 'end_date', label: 'Valid till', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: sel('pending', 'approved', 'rejected', 'expired', 'withdrawn') },
      { name: 'featured', label: 'Featured (sponsored)', type: 'bool' },
    ],
    actions: [
      { key: 'approve', label: 'Approve', set: { status: 'approved', approved_at: '$now', approved_by: '$user' }, tone: 'success', when: { column: 'status', in: ['pending', 'rejected'] }, permission: 'offer.review',
        notify: { event: 'offer_approved', title: 'Your offer is live', body: 'Buyers can now see and claim your offer.' } },
      { key: 'reject', label: 'Reject', set: { status: 'rejected' }, reasonColumn: 'rejection_reason', tone: 'danger', when: { column: 'status', in: ['pending', 'approved'] }, permission: 'offer.review' },
      { key: 'expire', label: 'Expire now', set: { status: 'expired' }, tone: 'neutral', when: { column: 'status', in: ['approved'] }, permission: 'offer.review' },
    ],
    permission: 'offer.review',
    canCreate: false, canDelete: true, softDelete: true,
  },
  {
    key: 'plans',
    table: 'subscription_plans',
    label: 'Plan',
    plural: 'Subscription plans',
    group: 'Dealers',
    description: 'What dealers can buy, and the limits attached to each plan.',
    titleColumn: 'name',
    columns: [
      { name: 'name', label: 'Plan' },
      { name: 'price', label: 'Price', type: 'money' },
      { name: 'duration_days', label: 'Days', type: 'number' },
      { name: 'lead_limit', label: 'Leads', type: 'number' },
      { name: 'offer_limit', label: 'Offers', type: 'number' },
      { name: 'active', label: 'Active', type: 'bool' },
    ],
    searchColumns: ['t.name', 't.code'],
    defaultSort: 't.sort_order, t.price',
    fields: [
      { name: 'name', label: 'Plan name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true },
      { name: 'price', label: 'Price (₹)', type: 'money', required: true },
      { name: 'duration_days', label: 'Duration (days)', type: 'number', required: true },
      { name: 'lead_limit', label: 'Included leads', type: 'number', required: true },
      { name: 'offer_limit', label: 'Live offer slots', type: 'number', required: true },
      { name: 'featured_placement', label: 'Includes featured placement', type: 'bool' },
      { name: 'features', label: 'Feature list (JSON array)', type: 'json' },
      { name: 'active', label: 'Available to buy', type: 'bool' },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
    ],
    permission: 'dealer.review',
    canCreate: true, canDelete: true,
  },
  {
    key: 'subscriptions',
    table: 'subscriptions',
    label: 'Subscription',
    plural: 'Subscriptions',
    group: 'Dealers',
    description: 'Active and expired dealer subscriptions.',
    titleColumn: 'id',
    listSelect: 'd.business_name, pl.name AS plan_name',
    listJoin: 'LEFT JOIN dealer_profiles d ON d.id = t.dealer_id LEFT JOIN subscription_plans pl ON pl.id = t.plan_id',
    columns: [
      { name: 'business_name', label: 'Dealer' },
      { name: 'plan_name', label: 'Plan' },
      STATUS_BADGE(),
      { name: 'leads_used', label: 'Leads used', type: 'number' },
      { name: 'starts_at', label: 'Start', type: 'date' },
      { name: 'ends_at', label: 'End', type: 'date' },
    ],
    searchColumns: ['d.business_name'],
    filters: [{ name: 'status', label: 'Status', column: 't.status', options: ['active', 'expired', 'cancelled'] }],
    defaultSort: 't.ends_at DESC',
    fields: [
      { name: 'status', label: 'Status', type: 'select', options: sel('active', 'expired', 'cancelled') },
      { name: 'ends_at', label: 'Ends at', type: 'datetime' },
      { name: 'leads_used', label: 'Leads used', type: 'number' },
      { name: 'auto_renew', label: 'Auto renew', type: 'bool' },
    ],
    permission: 'dealer.review',
    canCreate: false, canDelete: false,
  },
  {
    key: 'service-centres',
    table: 'service_centres',
    label: 'Service centre',
    plural: 'Service centres',
    group: 'Dealers',
    description: 'Workshop directory shown on the public service-centre page.',
    titleColumn: 'name',
    columns: [
      { name: 'name', label: 'Centre' },
      { name: 'city', label: 'City' },
      { name: 'phone', label: 'Phone' },
      { name: 'verified', label: 'Verified', type: 'bool' },
      STATUS_BADGE(),
    ],
    searchColumns: ['t.name', 't.city', 't.address'],
    defaultSort: 't.name',
    fields: [
      { name: 'name', label: 'Centre name', type: 'text', required: true },
      { name: 'brand_id', label: 'Authorised brand', type: 'relation', relation: { table: 'brands', labelColumn: 'name' } },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'city', label: 'City', type: 'text', required: true },
      { name: 'state', label: 'State', type: 'text' },
      { name: 'pincode', label: 'Pincode', type: 'text' },
      { name: 'services', label: 'Services (comma separated)', type: 'text' },
      { name: 'verified', label: 'Verified by staff', type: 'bool' },
      { name: 'featured', label: 'Featured', type: 'bool' },
      { name: 'status', label: 'Status', type: 'select', options: sel('active', 'inactive') },
      { name: 'is_demo', label: 'Demo data', type: 'bool' },
    ],
    permission: 'product.write',
    canCreate: true, canDelete: true, softDelete: true,
  },

  // ─────────────────────────── Content ───────────────────────────
  {
    key: 'reviews',
    table: 'reviews',
    label: 'Review',
    plural: 'Reviews',
    group: 'Content',
    description: 'Moderation queue. Nothing is published until a moderator approves it.',
    titleColumn: 'title',
    listSelect: 'p.name AS product_name, u.email AS author_email',
    listJoin: 'LEFT JOIN products p ON p.id = t.product_id LEFT JOIN users u ON u.id = t.user_id',
    columns: [
      { name: 'product_name', label: 'Model' },
      { name: 'rating', label: 'Rating', type: 'number' },
      { name: 'title', label: 'Title' },
      { name: 'author_email', label: 'Author' },
      STATUS_BADGE(),
      { name: 'created_at', label: 'Submitted', type: 'date' },
    ],
    searchColumns: ['p.name', 't.title', 't.body', 'u.email'],
    filters: [{ name: 'status', label: 'Status', column: 't.status', options: ['pending', 'approved', 'rejected'] }],
    defaultSort: "CASE t.status WHEN 'pending' THEN 0 ELSE 1 END, t.created_at DESC",
    fields: [
      { name: 'rating', label: 'Rating', type: 'number' },
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'pros', label: 'Pros', type: 'textarea' },
      { name: 'cons', label: 'Cons', type: 'textarea' },
      { name: 'body', label: 'Review body', type: 'longtext' },
      { name: 'status', label: 'Status', type: 'select', options: sel('pending', 'approved', 'rejected') },
    ],
    actions: [
      { key: 'approve', label: 'Approve', set: { status: 'approved', moderated_at: '$now', moderated_by: '$user' }, tone: 'success', when: { column: 'status', in: ['pending', 'rejected'] }, permission: 'review.moderate',
        notify: { event: 'review_published', title: 'Your review is published', body: 'Thanks — other buyers can now read it.' } },
      { key: 'reject', label: 'Reject', set: { status: 'rejected', moderated_at: '$now', moderated_by: '$user' }, reasonColumn: 'rejection_reason', tone: 'danger', when: { column: 'status', in: ['pending', 'approved'] }, permission: 'review.moderate' },
    ],
    permission: 'review.moderate',
    ownerColumn: 'user_id',
    canCreate: false, canDelete: true, softDelete: true,
  },
  {
    key: 'articles',
    table: 'articles',
    label: 'Article',
    plural: 'Guides & articles',
    group: 'Content',
    description: 'Buying guides, advice articles and the legal pages (category “legal”).',
    titleColumn: 'title',
    columns: [
      { name: 'title', label: 'Title' },
      { name: 'category', label: 'Category', type: 'badge' },
      { name: 'author_name', label: 'Author' },
      { name: 'published', label: 'Published', type: 'bool' },
      { name: 'view_count', label: 'Views', type: 'number' },
      { name: 'published_at', label: 'Date', type: 'date' },
    ],
    searchColumns: ['t.title', 't.slug', 't.excerpt'],
    filters: [{ name: 'category', label: 'Category', column: 't.category', options: ['buying_guide', 'ownership', 'ev', 'used', 'legal', 'news'] }],
    defaultSort: 't.published_at DESC',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'URL slug', type: 'text' },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea', help: 'Also used as the meta description.' },
      { name: 'category', label: 'Category', type: 'select', options: sel('buying_guide', 'ownership', 'ev', 'used', 'legal', 'news') },
      { name: 'cover_image', label: 'Cover image', type: 'image' },
      { name: 'content', label: 'Content', type: 'longtext', required: true, help: 'Use ## for headings, - for bullets, > for a callout.' },
      { name: 'author_name', label: 'Author name', type: 'text' },
      { name: 'reading_minutes', label: 'Reading time (min)', type: 'number' },
      { name: 'published', label: 'Published', type: 'bool' },
      { name: 'published_at', label: 'Publish date', type: 'datetime' },
    ],
    permission: 'article.write',
    canCreate: true, canDelete: true, softDelete: true,
    publicPath: '/guides',
  },
  {
    key: 'comparisons',
    table: 'comparisons',
    label: 'Comparison',
    plural: 'Curated comparisons',
    group: 'Content',
    description: 'Editor-picked comparisons shown on the homepage and compare page.',
    titleColumn: 'title',
    columns: [
      { name: 'title', label: 'Title' },
      { name: 'slug', label: 'Slug' },
      { name: 'view_count', label: 'Views', type: 'number' },
      { name: 'featured', label: 'Featured', type: 'bool' },
    ],
    searchColumns: ['t.title', 't.slug'],
    defaultSort: 't.view_count DESC',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'product_ids', label: 'Product IDs (comma separated, 2–4)', type: 'text', required: true },
      { name: 'featured', label: 'Featured', type: 'bool' },
    ],
    permission: 'article.write',
    canCreate: true, canDelete: true,
    publicPath: '/compare',
  },
  {
    key: 'seo',
    table: 'seo_metadata',
    label: 'SEO override',
    plural: 'SEO metadata',
    group: 'Content',
    description: 'Per-page title, description and canonical overrides.',
    titleColumn: 'path',
    columns: [
      { name: 'path', label: 'Path' },
      { name: 'title', label: 'Title' },
      { name: 'robots', label: 'Robots' },
      { name: 'updated_at', label: 'Updated', type: 'date' },
    ],
    searchColumns: ['t.path', 't.title'],
    defaultSort: 't.path',
    fields: [
      { name: 'path', label: 'Page path', type: 'text', required: true, placeholder: '/bikes/yamaha/mt-15-v2' },
      { name: 'title', label: 'Meta title', type: 'text' },
      { name: 'description', label: 'Meta description', type: 'textarea' },
      { name: 'keywords', label: 'Keywords', type: 'text' },
      { name: 'canonical', label: 'Canonical URL', type: 'text' },
      { name: 'og_image', label: 'Social share image', type: 'image' },
      { name: 'robots', label: 'Robots directive', type: 'select', options: sel('index,follow', 'noindex,follow', 'noindex,nofollow') },
    ],
    permission: 'article.write',
    canCreate: true, canDelete: true,
  },

  // ─────────────────────────── Growth ───────────────────────────
  {
    key: 'leads',
    table: 'leads',
    label: 'Lead',
    plural: 'Leads',
    group: 'Growth',
    description: 'Every enquiry across the platform, with the dealer it was routed to.',
    titleColumn: 'name',
    listSelect: 'd.business_name, p.name AS product_name',
    listJoin: 'LEFT JOIN dealer_profiles d ON d.id = t.dealer_id LEFT JOIN products p ON p.id = t.product_id',
    columns: [
      { name: 'name', label: 'Name' },
      { name: 'phone', label: 'Phone' },
      { name: 'lead_type', label: 'Type', type: 'badge' },
      { name: 'product_name', label: 'Model' },
      { name: 'business_name', label: 'Routed to' },
      STATUS_BADGE(),
      { name: 'created_at', label: 'Received', type: 'date' },
    ],
    searchColumns: ['t.name', 't.phone', 't.email', 't.city', 'p.name'],
    filters: [
      { name: 'lead_type', label: 'Type', column: 't.lead_type', options: ['best_price', 'contact_dealer', 'test_ride', 'finance', 'insurance', 'service', 'inspection', 'used_bike_enquiry', 'bulk_purchase', 'request_offer'] },
      { name: 'status', label: 'Status', column: 't.status', options: ['new', 'contacted', 'quoted', 'converted', 'lost', 'invalid'] },
    ],
    defaultSort: 't.created_at DESC',
    fields: [
      { name: 'status', label: 'Status', type: 'select', options: sel('new', 'contacted', 'quoted', 'converted', 'lost', 'invalid') },
      { name: 'dealer_id', label: 'Route to dealer', type: 'relation', relation: { table: 'dealer_profiles', labelColumn: 'business_name' } },
      { name: 'dealer_note', label: 'Note', type: 'textarea' },
      { name: 'value_estimate', label: 'Deal value estimate (₹)', type: 'money' },
    ],
    permission: 'lead.read',
    canCreate: false, canDelete: true, softDelete: true,
  },
  {
    key: 'ad-slots',
    table: 'ad_slots',
    label: 'Ad slot',
    plural: 'Ad slots',
    group: 'Growth',
    description: 'AdSense placements. Every slot is off until you switch it on and paste a unit ID.',
    titleColumn: 'name',
    columns: [
      { name: 'name', label: 'Slot' },
      { name: 'slot_key', label: 'Key' },
      { name: 'page_type', label: 'Page' },
      { name: 'ad_unit_id', label: 'Ad unit' },
      { name: 'enabled', label: 'Enabled', type: 'bool' },
    ],
    searchColumns: ['t.name', 't.slot_key'],
    defaultSort: 't.slot_key',
    fields: [
      { name: 'name', label: 'Display name', type: 'text', required: true },
      { name: 'slot_key', label: 'Slot key', type: 'text', required: true, help: 'Referenced in the page code. Do not change on an existing slot.' },
      { name: 'page_type', label: 'Page type', type: 'text' },
      { name: 'position', label: 'Position', type: 'text' },
      { name: 'ad_unit_id', label: 'AdSense ad unit ID', type: 'text' },
      { name: 'enabled', label: 'Enabled', type: 'bool' },
      { name: 'show_desktop', label: 'Show on desktop', type: 'bool' },
      { name: 'show_mobile', label: 'Show on mobile', type: 'bool' },
    ],
    permission: 'product.write',
    canCreate: true, canDelete: true,
  },
  {
    key: 'affiliate-links',
    table: 'affiliate_links',
    label: 'Affiliate link',
    plural: 'Affiliate links',
    group: 'Growth',
    description: 'Accessory and retailer links. Always labelled publicly; never affects scores.',
    titleColumn: 'title',
    columns: [
      { name: 'title', label: 'Title' },
      { name: 'retailer', label: 'Retailer' },
      { name: 'price', label: 'Price', type: 'money' },
      { name: 'click_count', label: 'Clicks', type: 'number' },
      STATUS_BADGE(),
    ],
    searchColumns: ['t.title', 't.retailer'],
    defaultSort: 't.click_count DESC',
    fields: [
      { name: 'title', label: 'Product title', type: 'text', required: true },
      { name: 'retailer', label: 'Retailer', type: 'text', required: true },
      { name: 'product_id', label: 'Related model', type: 'relation', relation: { table: 'products', labelColumn: 'name' } },
      { name: 'accessory_type', label: 'Accessory type', type: 'select', options: sel('helmet', 'gloves', 'jacket', 'luggage', 'care', 'electronics', 'other') },
      { name: 'normal_url', label: 'Plain URL', type: 'text' },
      { name: 'affiliate_url', label: 'Affiliate URL', type: 'text', help: 'Never rendered in page markup — used only by the click redirect.' },
      { name: 'price', label: 'Price (₹)', type: 'money' },
      { name: 'commission_percent', label: 'Commission (%)', type: 'number', step: 0.1 },
      { name: 'image_url', label: 'Image', type: 'image' },
      { name: 'status', label: 'Status', type: 'select', options: sel('active', 'paused') },
    ],
    permission: 'product.write',
    canCreate: true, canDelete: true, softDelete: true,
  },
  {
    key: 'payments',
    table: 'payments',
    label: 'Payment',
    plural: 'Payments',
    group: 'Growth',
    description: 'Payment records. With no gateway configured these stay pending until you confirm them.',
    titleColumn: 'id',
    listSelect: 'u.email AS user_email, d.business_name',
    listJoin: 'LEFT JOIN users u ON u.id = t.user_id LEFT JOIN dealer_profiles d ON d.id = t.dealer_id',
    columns: [
      { name: 'created_at', label: 'Date', type: 'date' },
      { name: 'purpose', label: 'Purpose', type: 'badge' },
      { name: 'user_email', label: 'User' },
      { name: 'business_name', label: 'Dealer' },
      { name: 'amount', label: 'Amount', type: 'money' },
      STATUS_BADGE(),
    ],
    searchColumns: ['u.email', 'd.business_name', 't.id'],
    filters: [{ name: 'status', label: 'Status', column: 't.status', options: ['created', 'pending', 'paid', 'failed', 'refunded', 'cancelled'] }],
    defaultSort: 't.created_at DESC',
    fields: [
      { name: 'status', label: 'Status', type: 'select', options: sel('created', 'pending', 'paid', 'failed', 'refunded', 'cancelled') },
      { name: 'failure_reason', label: 'Note', type: 'text' },
    ],
    actions: [
      { key: 'mark_paid', label: 'Mark received', set: { status: 'paid' }, tone: 'success', when: { column: 'status', in: ['created', 'pending', 'failed'] } },
      { key: 'refund', label: 'Mark refunded', set: { status: 'refunded' }, reasonColumn: 'failure_reason', tone: 'danger', when: { column: 'status', in: ['paid'] } },
    ],
    permission: '*',
    canCreate: false, canDelete: false,
  },

  // ─────────────────────────── Data ───────────────────────────
  {
    key: 'data-sources',
    table: 'data_sources',
    label: 'Data source',
    plural: 'Data sources',
    group: 'Data',
    description: 'Where specifications and prices come from. A failing source never deletes existing data.',
    titleColumn: 'name',
    columns: [
      { name: 'name', label: 'Source' },
      { name: 'source_type', label: 'Type', type: 'badge' },
      { name: 'trust_level', label: 'Trust', type: 'number' },
      { name: 'priority', label: 'Priority', type: 'number' },
      STATUS_BADGE(),
      { name: 'last_success_at', label: 'Last success', type: 'date' },
      { name: 'error_count', label: 'Errors', type: 'number' },
    ],
    searchColumns: ['t.name', 't.slug'],
    defaultSort: 't.priority DESC',
    fields: [
      { name: 'name', label: 'Source name', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'source_type', label: 'Type', type: 'select', required: true, options: sel('manufacturer', 'partner_feed', 'verified_source', 'admin_manual', 'csv_import', 'approved_secondary') },
      { name: 'endpoint', label: 'Endpoint / URL', type: 'text' },
      { name: 'auth_env_key', label: 'API key env variable', type: 'text', help: 'Name of the environment variable holding the key — never paste the key itself.' },
      { name: 'priority', label: 'Priority', type: 'number', help: 'Higher wins when two sources disagree.' },
      { name: 'trust_level', label: 'Trust level (0–100)', type: 'number' },
      { name: 'schedule_cron', label: 'Schedule (cron)', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', options: sel('active', 'paused', 'failing') },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
    permission: 'data.review',
    canCreate: true, canDelete: true, softDelete: true,
  },
  {
    key: 'changes',
    table: 'data_change_logs',
    label: 'Data change',
    plural: 'Change approvals',
    group: 'Data',
    description: 'Proposed changes from imports and pipelines. Nothing is applied until approved.',
    titleColumn: 'field_name',
    columns: [
      { name: 'entity_type', label: 'Entity', type: 'badge' },
      { name: 'entity_id', label: 'Entity ID' },
      { name: 'field_name', label: 'Field' },
      { name: 'old_value', label: 'Current' },
      { name: 'new_value', label: 'Proposed' },
      { name: 'source_name', label: 'Source' },
      STATUS_BADGE(),
    ],
    searchColumns: ['t.entity_id', 't.field_name', 't.source_name'],
    filters: [{ name: 'status', label: 'Status', column: 't.status', options: ['pending', 'approved', 'rejected', 'applied'] }],
    defaultSort: "CASE t.status WHEN 'pending' THEN 0 ELSE 1 END, t.created_at DESC",
    fields: [
      { name: 'new_value', label: 'Proposed value', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', options: sel('pending', 'approved', 'rejected', 'applied') },
      { name: 'note', label: 'Note', type: 'textarea' },
    ],
    permission: 'data.review',
    canCreate: false, canDelete: true,
  },
  {
    key: 'imports',
    table: 'data_import_jobs',
    label: 'Import job',
    plural: 'Import history',
    group: 'Data',
    description: 'Every CSV import, with the counts of what was created, updated and skipped.',
    titleColumn: 'filename',
    columns: [
      { name: 'filename', label: 'File' },
      { name: 'job_type', label: 'Type', type: 'badge' },
      { name: 'rows_total', label: 'Rows', type: 'number' },
      { name: 'rows_imported', label: 'Imported', type: 'number' },
      { name: 'rows_invalid', label: 'Invalid', type: 'number' },
      { name: 'rows_duplicate', label: 'Skipped', type: 'number' },
      STATUS_BADGE(),
      { name: 'created_at', label: 'When', type: 'date' },
    ],
    searchColumns: ['t.filename'],
    defaultSort: 't.created_at DESC',
    fields: [{ name: 'status', label: 'Status', type: 'readonly' }],
    permission: 'data.review',
    canCreate: false, canDelete: true,
  },

  // ─────────────────────────── People ───────────────────────────
  {
    key: 'users',
    table: 'users',
    label: 'User',
    plural: 'Users & roles',
    group: 'People',
    description: 'Accounts and their roles. Changing a role changes what that person can do immediately.',
    titleColumn: 'email',
    columns: [
      { name: 'full_name', label: 'Name' },
      { name: 'email', label: 'Email' },
      { name: 'role', label: 'Role', type: 'badge' },
      { name: 'city', label: 'City' },
      STATUS_BADGE(),
      { name: 'created_at', label: 'Joined', type: 'date' },
    ],
    searchColumns: ['t.email', 't.full_name', 't.phone'],
    filters: [
      { name: 'role', label: 'Role', column: 't.role', options: ['user', 'dealer', 'verifier', 'moderator', 'admin'] },
      { name: 'status', label: 'Status', column: 't.status', options: ['active', 'suspended'] },
    ],
    defaultSort: 't.created_at DESC',
    fields: [
      { name: 'full_name', label: 'Full name', type: 'text' },
      { name: 'email', label: 'Email', type: 'text', required: true },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'city', label: 'City', type: 'text' },
      { name: 'role', label: 'Role', type: 'select', required: true, options: sel('user', 'dealer', 'verifier', 'moderator', 'admin'), help: 'Admin can do everything. Moderator handles content and approvals. Verifier handles used-bike and dealer checks.' },
      { name: 'status', label: 'Status', type: 'select', options: sel('active', 'suspended') },
    ],
    actions: [
      { key: 'suspend', label: 'Suspend account', set: { status: 'suspended' }, reasonColumn: 'suspension_reason', tone: 'danger', when: { column: 'status', in: ['active'] }, permission: '*',
        notify: { event: 'verification_result', title: 'Your account has been suspended', body: 'Contact support if you believe this is a mistake.' } },
      { key: 'reactivate', label: 'Reactivate', set: { status: 'active' }, tone: 'success', when: { column: 'status', in: ['suspended'] }, permission: '*' },
    ],
    ownerColumn: 'id',
    permission: '*',
    canCreate: false, canDelete: true, softDelete: true,
  },
  {
    key: 'audit-logs',
    table: 'audit_logs',
    label: 'Audit entry',
    plural: 'Audit log',
    group: 'People',
    description: 'Immutable record of every staff action. Read-only by design.',
    titleColumn: 'action',
    columns: [
      { name: 'created_at', label: 'When', type: 'date' },
      { name: 'actor_email', label: 'Who' },
      { name: 'actor_role', label: 'Role', type: 'badge' },
      { name: 'action', label: 'Action' },
      { name: 'entity_type', label: 'Entity' },
      { name: 'entity_id', label: 'Entity ID' },
      { name: 'ip', label: 'IP' },
    ],
    searchColumns: ['t.actor_email', 't.action', 't.entity_id'],
    defaultSort: 't.created_at DESC',
    fields: [],
    permission: '*',
    canCreate: false, canDelete: false,
  },
  {
    key: 'notifications',
    table: 'notifications',
    label: 'Notification',
    plural: 'Notifications',
    group: 'People',
    description: 'Everything the platform has sent or queued, across every channel.',
    titleColumn: 'title',
    listSelect: 'u.email AS user_email',
    listJoin: 'LEFT JOIN users u ON u.id = t.user_id',
    columns: [
      { name: 'created_at', label: 'When', type: 'date' },
      { name: 'user_email', label: 'To' },
      { name: 'channel', label: 'Channel', type: 'badge' },
      { name: 'event_type', label: 'Event' },
      { name: 'title', label: 'Title' },
      { name: 'delivery_status', label: 'Delivery', type: 'badge' },
    ],
    searchColumns: ['u.email', 't.title', 't.event_type'],
    filters: [{ name: 'channel', label: 'Channel', column: 't.channel', options: ['in_app', 'email', 'sms'] }],
    defaultSort: 't.created_at DESC',
    fields: [],
    permission: '*',
    canCreate: false, canDelete: true,
  },
];

export const ADMIN_GROUPS = ['Catalogue', 'Marketplace', 'Dealers', 'Content', 'Growth', 'Data', 'People'];

export function getResource(key: string): AdminResource | undefined {
  return ADMIN_RESOURCES.find((r) => r.key === key);
}
